name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
#       -
#         name: Set up QEMU
#         uses: docker/setup-qemu-action@v2
#       -
#         name: Build the tagged Docker image
#         run: |
#           pwd
#           cd project/techtrends/
#           docker build . --file Dockerfile --tag my-image-name:techtrends
      -
        name: Set  up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: project/techtrends/
          file: project/techtrends/Dockerfile
          push: true
          tags: my-image-name:techtrends
